// SPDX-FileCopyrightText: 2026 Kofeecheks
// SPDX-License-Identifier: LicenseRef-Kofeecheks
using System; // DS-14
using System.Collections.Generic; // DS-14
using System.Linq; // DS-14
using Content.Shared.Audio.Jukebox;
using Content.Shared.DeadSpace._Soyuz.Jukebox;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement; // DS-14
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio.Components;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.DeadSpace._Soyuz.Jukebox;

[GenerateTypedNameReferences]
public sealed partial class JukeboxMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!; // DS-14
    private AudioSystem _audioSystem;
    // DS-14 Start: The menu now owns filtered list state and a local volume preview so
    // dragging the slider feels immediate before replicated component state catches up.
    private JukeboxSystem _jukeboxSystem;
    private readonly List<JukeboxPrototype> _allSongs = new();

    /// <summary>
    /// Are we currently 'playing' or paused for the play / pause button.
    /// </summary>
    private bool _playState;
    private bool _updatingSongList;
    private ProtoId<JukeboxPrototype>? _selectedSongId;

    /// <summary>
    /// True if playing, false if paused.
    /// </summary>
    public event Action<bool>? OnPlayPressed;
    public event Action? OnNextPressed;
    public event Action? OnPreviousPressed;
    public event Action<bool>? OnShuffleToggled;
    public event Action<bool>? OnRepeatToggled;
    public event Action<ProtoId<JukeboxPrototype>>? OnSongSelected;
    public event Action<float>? SetTime;
    public event Action<float>? SetVolume;

    private EntityUid _jukebox;
    private EntityUid? _audio;

    private float _lockTimer;
    private float _volume = JukeboxVolume.DefaultValue;
    private float _lastSentVolume = JukeboxVolume.DefaultValue;
    private float _volumeSendAccumulator;
    private float _volumeInteractionTimer;
    private bool _pendingVolumeSend;
    private bool _awaitingVolumeSync;
    private bool _updatingVolume;
    private const float VolumeSendInterval = 0.12f;
    private const float VolumeSendTolerance = 0.01f;
    private const float VolumeInteractionHoldTime = 0.2f;
    private const string PlayIconTexturePath = "/Textures/Interface/AdminActions/play.png";
    private const string PauseIconTexturePath = "/Textures/Interface/AdminActions/pause.png";
    private const string VolumeIconRsiPath = "/Textures/Interface/Actions/actions_borg.rsi";
    private const string VolumeIconState = "musical-module";
    // DS-14 End

    public JukeboxMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _audioSystem = _entManager.System<AudioSystem>();
        // DS-14 Start: XAML only defines the controls; the menu wires search, richer
        // transport buttons, and slider throttling locally.
        _jukeboxSystem = _entManager.System<JukeboxSystem>();
        SetVolumeIcon();
        VolumeSlider.MinValue = JukeboxVolume.MinValue;
        VolumeSlider.MaxValue = JukeboxVolume.MaxValue;
        VolumeSlider.Page = 0f;

        MusicList.OnItemSelected += args =>
        {
            if (_updatingSongList)
                return;

            var entry = MusicList[args.ItemIndex];

            if (entry.Metadata is not string juke)
                return;

            OnSongSelected?.Invoke(juke);
        };

        PlayButton.OnPressed += args =>
        {
            OnPlayPressed?.Invoke(!_playState);
        };

        PreviousButton.OnPressed += _ => OnPreviousPressed?.Invoke();
        NextButton.OnPressed += _ => OnNextPressed?.Invoke();
        ShuffleButton.OnToggled += args => OnShuffleToggled?.Invoke(args.Pressed);
        RepeatButton.OnToggled += args => OnRepeatToggled?.Invoke(args.Pressed);
        SearchInput.OnTextChanged += _ => RefreshSongList();
        PlaybackSlider.OnReleased += PlaybackSliderKeyUp;
        VolumeSlider.OnValueChanged += _ => OnVolumeSliderChanged();
        // DS-14 End

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio), force: true);
        SetVolumeSlider(_volume, force: true);
    }

    // DS-14 Start: When the same jukebox window is reopened, restore any client-only
    // volume override instead of snapping back to replicated state immediately.
    public void SetJukebox(EntityUid jukebox)
    {
        _jukebox = jukebox;

        if (!_jukeboxSystem.TryGetVolumeOverride(jukebox, out var volume))
            return;

        _awaitingVolumeSync = true;
        SetVolumeSlider(volume, force: true);
    }
    // DS-14 End

    public void SetAudioStream(EntityUid? audio)
    {
        _audio = audio;
        if (HasActiveLocalVolumeOverride)
            TryApplyLocalVolume(_volume);
    }

    private void PlaybackSliderKeyUp(Slider args)
    {
        SetTime?.Invoke(PlaybackSlider.Value);
        _lockTimer = 0.5f;
    }

    /// <summary>
    /// Re-populates the list of jukebox prototypes available.
    /// </summary>
    public void Populate(IEnumerable<JukeboxPrototype> jukeboxProtos)
    {
        // DS-14 Start: Keep a sorted source list so search only filters the visible items
        // and the same ordering is reused by selection refresh.
        _allSongs.Clear();
        _allSongs.AddRange(jukeboxProtos);
        _allSongs.Sort(static (left, right) => string.Compare(left.Name, right.Name, StringComparison.OrdinalIgnoreCase));
        RefreshSongList();
        // DS-14 End
    }

    public void SetPlayPauseButton(bool playing, bool force = false)
    {
        if (_playState == playing && !force)
            return;

        _playState = playing;

        // DS-14 Start: The play button is icon-based now, so the tooltip carries the
        // action text that used to be visible on the old text button.
        if (playing)
        {
            PlayIcon.TexturePath = PauseIconTexturePath;
            PlayButton.ToolTip = Loc.GetString("jukebox-menu-buttonpause");
            return;
        }

        PlayIcon.TexturePath = PlayIconTexturePath;
        PlayButton.ToolTip = Loc.GetString("jukebox-menu-buttonplay");
        // DS-14 End
    }

    // DS-14 Start: Selection sync keys on the prototype id so filtered lists, reloads,
    // and playback changes all keep the same row highlighted.
    public void SetSelectedSong(ProtoId<JukeboxPrototype>? songId, string? name, float length)
    {
        var resetSlider = _selectedSongId != songId || Math.Abs(PlaybackSlider.MaxValue - length) > 0.05f;
        _selectedSongId = songId;
        SetSelectedSongText(name);
        PlaybackSlider.MaxValue = length;

        if (resetSlider)
            PlaybackSlider.SetValueWithoutEvent(0);

        RefreshSelection();
    }

    public void SetShuffleEnabled(bool enabled)
    {
        ShuffleButton.Pressed = enabled;
    }

    public void SetRepeatEnabled(bool enabled)
    {
        RepeatButton.Pressed = enabled;
    }

    public void SetVolumeSlider(float volume, bool force = false)
    {
        volume = JukeboxVolume.Clamp(volume);

        if (!force && HasActiveLocalVolumeOverride)
        {
            if (_awaitingVolumeSync && Math.Abs(_volume - volume) <= VolumeSendTolerance)
            {
                _awaitingVolumeSync = false;
            }
            else
            {
                return;
            }
        }

        if (!force && Math.Abs(_volume - volume) <= VolumeSendTolerance)
            return;

        _volume = volume;
        _updatingVolume = true;
        var sliderValue = 1f - volume;
        VolumeSlider.ValueTarget = sliderValue;
        VolumeSlider.SetValueWithoutEvent(sliderValue);
        _updatingVolume = false;
        UpdateVolumeLabel();
        TryApplyLocalVolume(volume);
    }

    private void SetVolumeIcon()
    {
        var rsi = _resourceCache.GetResource<RSIResource>(VolumeIconRsiPath).RSI;

        if (rsi.TryGetState(VolumeIconState, out var state))
            VolumeIcon.Texture = state.Frame0;
    }
    // DS-14 End

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lockTimer > 0f)
        {
            _lockTimer -= args.DeltaSeconds;
        }

        // DS-14 Start: Slider drags preview volume immediately on the client, but sends
        // to the server are batched here so we do not spam network traffic every frame.
        if (_pendingVolumeSend)
        {
            _volumeSendAccumulator += args.DeltaSeconds;
            if (_volumeSendAccumulator >= VolumeSendInterval)
            {
                FlushPendingVolume();
            }
        }

        if (_volumeInteractionTimer > 0f)
            _volumeInteractionTimer = Math.Max(0f, _volumeInteractionTimer - args.DeltaSeconds);
        // DS-14 End

        PlaybackSlider.Disabled = _lockTimer > 0f;

        if (_entManager.TryGetComponent(_audio, out AudioComponent? audio))
        {
            DurationLabel.Text = $@"{TimeSpan.FromSeconds(audio.PlaybackPosition):mm\:ss} / {_audioSystem.GetAudioLength(audio.FileName):mm\:ss}";
        }
        else
        {
            DurationLabel.Text = $@"00:00 / {TimeSpan.FromSeconds(PlaybackSlider.MaxValue):mm\:ss}";  // DS-14
        }

        if (PlaybackSlider.Grabbed)
            return;

        if (audio != null || _entManager.TryGetComponent(_audio, out audio))
        {
            PlaybackSlider.SetValueWithoutEvent(audio.PlaybackPosition);
        }
        else
        {
            PlaybackSlider.SetValueWithoutEvent(0f);
        }

        SetPlayPauseButton(_audioSystem.IsPlaying(_audio, audio));
    }

    // DS-14 Start: These helpers isolate local preview state from replicated state. The
    // menu can feel instant while dragging, and the override is retired once sync lands.
    public void SetSelectedSongText(string? text)
    {
        if (!string.IsNullOrEmpty(text))
        {
            SongName.Text = text;
        }
        else
        {
            SongName.Text = "---";
        }
    }

    public bool TryGetLocalVolumeOverride(out float volume)
    {
        if (!HasActiveLocalVolumeOverride)
        {
            volume = default;
            return false;
        }

        volume = _volume;
        return true;
    }

    public void CommitVolumeState()
    {
        if (_pendingVolumeSend)
            FlushPendingVolume();

        if (HasActiveLocalVolumeOverride)
        {
            _jukeboxSystem.SetVolumeOverride(_jukebox, _volume);
            return;
        }

        _jukeboxSystem.ClearVolumeOverride(_jukebox);
    }

    private void RefreshSongList()
    {
        _updatingSongList = true;
        MusicList.Clear();

        var filter = SearchInput.Text.Trim();
        foreach (var song in _allSongs)
        {
            if (!string.IsNullOrEmpty(filter) &&
                !song.Name.Contains(filter, StringComparison.OrdinalIgnoreCase) &&
                !song.ID.Contains(filter, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var item = MusicList.AddItem(song.Name, metadata: song.ID);
            item.Selected = _selectedSongId == song.ID;
        }

        _updatingSongList = false;
    }

    private void RefreshSelection()
    {
        _updatingSongList = true;
        foreach (var item in MusicList)
        {
            item.Selected = item.Metadata is string songId && _selectedSongId == songId;
        }

        _updatingSongList = false;
    }

    private void OnVolumeSliderChanged()
    {
        if (_updatingVolume)
            return;

        _volumeInteractionTimer = VolumeInteractionHoldTime;
        _volume = JukeboxVolume.Clamp(1f - VolumeSlider.Value);
        _jukeboxSystem.SetVolumeOverride(_jukebox, _volume);
        UpdateVolumeLabel();
        TryApplyLocalVolume(_volume);

        if (Math.Abs(_volume - _lastSentVolume) <= VolumeSendTolerance)
            return;

        _pendingVolumeSend = true;
    }

    private void FlushPendingVolume()
    {
        _volumeSendAccumulator = 0f;

        if (Math.Abs(_volume - _lastSentVolume) <= VolumeSendTolerance)
        {
            _pendingVolumeSend = false;
            return;
        }

        _lastSentVolume = _volume;
        _pendingVolumeSend = false;
        _awaitingVolumeSync = true;
        SetVolume?.Invoke(_volume);
    }

    private void UpdateVolumeLabel()
    {
        VolumeValueLabel.Text = $"{(int) MathF.Round(_volume * 100f)}%";
    }

    private bool HasActiveLocalVolumeOverride =>
        _volumeInteractionTimer > 0f || _pendingVolumeSend || _awaitingVolumeSync;

    private void TryApplyLocalVolume(float volume)
    {
        _jukeboxSystem.ApplyClientVolume(_audio, volume);
    }
    // DS-14 End
}

public sealed class JukeboxBoundUserInterface : BoundUserInterface
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    [ViewVariables]
    private JukeboxMenu? _menu;
    private bool _volumeCommitted;

    public JukeboxBoundUserInterface(EntityUid owner, Enum uiKey) : base(owner, uiKey)
    {
        IoCManager.InjectDependencies(this);
    }

    protected override void Open()
    {
        base.Open();

        _menu = this.CreateWindow<JukeboxMenu>();
        _menu.SetJukebox(Owner);
        _menu.OnClose += CommitVolume;
        _menu.OnPlayPressed += playing =>
            SendMessage(playing ? new JukeboxPlayingMessage() : new JukeboxPauseMessage());
        _menu.OnPreviousPressed += () => SendMessage(new JukeboxPreviousMessage());
        _menu.OnNextPressed += () => SendMessage(new JukeboxNextMessage());
        _menu.OnShuffleToggled += enabled => SendMessage(new JukeboxShuffleMessage(enabled));
        _menu.OnRepeatToggled += enabled => SendMessage(new JukeboxRepeatMessage(enabled));
        _menu.OnSongSelected += song => SendMessage(new JukeboxSelectedMessage(song));
        _menu.SetTime += SetTime;
        _menu.SetVolume += volume => SendMessage(new JukeboxSetVolumeMessage(volume));

        PopulateMusic();
        Reload();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            CommitVolume();

        base.Dispose(disposing);
    }

    public void Reload()
    {
        if (_menu == null || !EntMan.TryGetComponent(Owner, out JukeboxComponent? jukebox))
            return;

        _menu.SetAudioStream(jukebox.AudioStream);
        _menu.SetShuffleEnabled(jukebox.ShuffleEnabled);
        _menu.SetRepeatEnabled(jukebox.RepeatEnabled);
        _menu.SetVolumeSlider(jukebox.Volume);

        if (_prototypeManager.Resolve(jukebox.SelectedSongId, out var song))
        {
            var duration = EntMan.System<AudioSystem>().GetAudioLength(song.Path.Path.ToString());
            _menu.SetSelectedSong(jukebox.SelectedSongId, song.Name, (float) duration.TotalSeconds);
            return;
        }

        _menu.SetSelectedSong(null, string.Empty, 0f);
    }

    public void PopulateMusic()
    {
        _menu?.Populate(_prototypeManager.EnumeratePrototypes<JukeboxPrototype>());
    }

    public bool TryGetLocalVolumeOverride(out float volume)
    {
        if (_menu != null)
            return _menu.TryGetLocalVolumeOverride(out volume);

        volume = default;
        return false;
    }

    private void SetTime(float time)
    {
        if (EntMan.TryGetComponent(Owner, out JukeboxComponent? jukebox) &&
            EntMan.TryGetComponent(jukebox.AudioStream, out AudioComponent? audio))
        {
            audio.PlaybackPosition = time;
        }

        SendMessage(new JukeboxSetTimeMessage(time));
    }

    private void CommitVolume()
    {
        if (_volumeCommitted || _menu == null)
            return;

        _volumeCommitted = true;
        _menu.CommitVolumeState();
    }
}