- type: job
  id: OfficerGS
  name: job-name-OfficerGS
  description: job-description-OfficerGS
  playTimeTracker: JobOfficerGS
  whitelisted: True
  startingGear: OfficerGSGear
  icon: "JobIconNanotrasen"
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant, DeathRattleImplantCentcomm ]
  - !type:AddComponentSpecial
    components:
    - type: AntagImmune
    - type: ZombieImmune
    - type: NpcFactionMember
      factions:
      - CentralCommand
    - type: Skill
      group: ALL
  supervisors: job-supervisors-centcom-administrator

- type: startingGear
  id: OfficerGSGear
  equipment:
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatCentcomOfficer
    head: ClothingHeadHatBeretCentcomNaval
    id: CentcomPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltSecurityFilled
    jumpsuit: ClothingUniformJumpsuitCentcomOfficer
    neck: SecurityWhistle
    back: ClothingBackpackMilitarySatchel
    shoes: ClothingShoesBootsJackFilled
    eyes: ClothingEyesGlassesHiddenSecurity
    pocket1: TelescopicShield
    pocket2: WeaponPistolX01
  storage:
     back:
     - BoxZiptie
     - MagazineLightRifle
     - MagazineLightRifle
     - MagazineLightRifle
     - WeaponRifleAKMCY

- type: chameleonOutfit
  id: OfficerGSChameleonOutfit
  job: OfficerGS
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomOfficer
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatBeretCentcomNaval
    mask: ClothingMaskGasSecurity
    eyes: ClothingEyesGlassesHiddenSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterCoatCentcomOfficer
    ears: ClothingHeadsetAltCentCom
    back: ClothingBackpackMilitarySatchel
