- type: latheRecipePack
  id: ExperimentalCloning
  recipes:
  - CloningConsoleComputerCircuitboardSoyuz
  - ExperimentalCloningPodMachineCircuitboard
  - MedicalScannerMachineCircuitboardSoyuz

- type: latheRecipePack
  id: PolaroidCamera
  recipes:
  - PolaroidCamera
  - PolaroidCartridge