- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Aspid
  - Bagel
  - Barratry
  - Box
  - Cluster #DS14-Soyuz-enabled
  - Cog
  - Convex
  - Core
  # - CorvaxAstra # DS14-Soyuz-disabled
  # - CorvaxAvrite # DS14-Soyuz-disabled
  # - CorvaxChloris # DS14-Soyuz-disabled
  # - CorvaxDelta # DS14-Soyuz-disabled
  # - CorvaxGlacier # DS14-Soyuz-disabled
  # - CorvaxPaper # Removed by Liv
  - CorvaxSilly
  # - CorvaxSpectrum # DS14-Soyuz-disabled
  # - CorvaxGlacier # DS14-Soyuz-disabled
  - CorvaxPearl
  - Elkridge
  - Fland
  - Gate
  - Ishimura
  - Gemini #DS14
  - Loop #DS14-Soyuz-enabled
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Packed
  - Plasma 
  - Reach #DS14-Soyuz-enabled
  # - Exo # map prototype is commented out
  - Saltern
  - Snowball # DS14-Soyuz
  - Train
