// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT
using System;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.GamePreset;

[GenerateTypedNameReferences]
public sealed partial class LowPlayerPresetWindow : DefaultWindow
{
    public event Action<string?>? OnPresetSelected;

    private string? _selectedPresetId;
    private readonly List<Button> _radioButtons = new();

    public LowPlayerPresetWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SaveButton.OnPressed += _ => Save();
    }

    public void LoadPresets(List<string> presetIds, Dictionary<string, string> names, string? currentPresetId)
    {
        PresetList.RemoveAllChildren();
        _radioButtons.Clear();
        _selectedPresetId = currentPresetId;

        var group = new ButtonGroup();

        foreach (var id in presetIds)
        {
            var radio = new Button
            {
                Text = names.GetValueOrDefault(id, id),
                ToggleMode = true,
                Group = group,
                Pressed = id == currentPresetId
            };
            radio.OnPressed += _ =>
            {
                _selectedPresetId = id;
            };
            _radioButtons.Add(radio);
            PresetList.AddChild(radio);
        }
    }

    private void Save()
    {
        OnPresetSelected?.Invoke(_selectedPresetId);
        Close();
    }
}