// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Collections.Generic;
using System.Linq;
using Content.Client.DeadSpace.Administration.GamePreset;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.GamePreset;

[GenerateTypedNameReferences]
public sealed partial class PresetSettingsWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private GamePresetClientSystem _system = default!;
    private List<string> _currentWhitelist = new();
    private string? _lowPlayerPresetId;

    public PresetSettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _system = _entityManager.System<GamePresetClientSystem>();
        SaveSettingsButton.OnPressed += _ => SaveSettings();

        EnableMaxRdmRowCheckBox.OnToggled += _ => UpdateSpinBoxes();
        WhitelistButton.OnPressed += _ => OpenWhitelistWindow();
        SelectLowPlayerPresetButton.OnPressed += _ => OpenLowPlayerPresetWindow();
    }

    public void LoadSettings(
        int maxRdmRow,
        int voteDurationSeconds,
        bool disableOoc,
        bool preventRepeat,
        bool checkPlayerLimit,
        List<string> whitelistModeIds,
        bool enableLowPlayerPreset,
        int lowPlayerThreshold,
        string? lowPlayerPresetId)
    {
        EnableMaxRdmRowCheckBox.Pressed = maxRdmRow > 0;
        MaxRdmRowSpinBox.Value = maxRdmRow > 0 ? maxRdmRow : 2;
        VoteDurationSpinBox.Value = voteDurationSeconds > 0 ? voteDurationSeconds : 30;
        DisableOocCheckBox.Pressed = disableOoc;
        PreventRepeatCheckBox.Pressed = preventRepeat;
        CheckPlayerLimitCheckBox.Pressed = checkPlayerLimit;
        EnableLowPlayerCheckBox.Pressed = enableLowPlayerPreset;
        LowPlayerThresholdSpinBox.Value = lowPlayerThreshold;
        _lowPlayerPresetId = lowPlayerPresetId;
        _currentWhitelist = whitelistModeIds ?? new List<string>();

        UpdateSelectedPresetLabel();
        UpdateSpinBoxes();
    }

    private void UpdateSpinBoxes()
    {
        MaxRdmRowSpinBox.ModulateSelfOverride = EnableMaxRdmRowCheckBox.Pressed ? null : Color.FromHex("#666666");
    }

    private void SaveSettings()
    {
        var maxRow = EnableMaxRdmRowCheckBox.Pressed ? MaxRdmRowSpinBox.Value : 0;
        var voteDuration = VoteDurationSpinBox.Value;
        var disableOoc = DisableOocCheckBox.Pressed;
        var preventRepeat = PreventRepeatCheckBox.Pressed;
        var checkPlayerLimit = CheckPlayerLimitCheckBox.Pressed;
        var enableLowPlayer = EnableLowPlayerCheckBox.Pressed;
        var lowPlayerThreshold = LowPlayerThresholdSpinBox.Value;

        _system.UpdatePresetSettings(
            maxRow,
            voteDuration,
            disableOoc,
            preventRepeat,
            checkPlayerLimit,
            _currentWhitelist,
            enableLowPlayer,
            lowPlayerThreshold,
            _lowPlayerPresetId);

        Close();
    }

    private void OpenWhitelistWindow()
    {
        var clientSystem = _entityManager.System<GamePresetClientSystem>();
        var window = new WhitelistWindow();
        window.LoadModes(
            clientSystem.PresetNames.Keys.Where(k => !k.StartsWith("custom_")).ToList(),
            clientSystem.PresetNames,
            _currentWhitelist);
        window.OnWhitelistSaved += (selected) =>
        {
            _currentWhitelist = selected;
        };
        window.OpenCentered();
    }

    private void OpenLowPlayerPresetWindow()
    {
        var clientSystem = _entityManager.System<GamePresetClientSystem>();
        var window = new LowPlayerPresetWindow();
        window.LoadPresets(
            clientSystem.PresetNames.Keys.Where(k => k.StartsWith("custom_")).ToList(), // только кастомные пресеты
            clientSystem.PresetNames,
            _lowPlayerPresetId);
        window.OnPresetSelected += (selectedId) =>
        {
            _lowPlayerPresetId = selectedId;
            UpdateSelectedPresetLabel();
        };
        window.OpenCentered();
    }

    private void UpdateSelectedPresetLabel()
    {
        if (string.IsNullOrEmpty(_lowPlayerPresetId))
        {
            SelectedLowPlayerPresetLabel.Text = Loc.GetString("game-preset-settings-no-preset-selected");
            return;
        }

        var clientSystem = _entityManager.System<GamePresetClientSystem>();
        SelectedLowPlayerPresetLabel.Text = clientSystem.PresetNames.GetValueOrDefault(_lowPlayerPresetId, _lowPlayerPresetId);
    }
}