// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-fobos/master/LICENSE.TXT

using System.Linq;
using Robust.Client.UserInterface.CustomControls;
using Content.Shared.DeadSpace.CentComm;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client.DeadSpace.CentComm;

[GenerateTypedNameReferences]
public sealed partial class CentCommTransferWindow : DefaultWindow
{
    private string[] _parallaxes = [];
    private string[] _weather = [];
    public event Action<CentCommTransferRequest>? OnTransfer;

    public CentCommTransferWindow()
    {
        RobustXamlLoader.Load(this);
        foreach (var preset in Enum.GetValues<CentCommTemperature>())
            TemperatureSelector.AddItem(Loc.GetString($"centcomm-transfer-temperature-{preset.ToString().ToLowerInvariant()}"), (int) preset);
        TemperatureSelector.SelectId((int) CentCommTemperature.Normal);
        TemperatureSelector.OnItemSelected += args =>
        {
            TemperatureSelector.SelectId(args.Id);
            CustomTemperatureRow.Visible = args.Id == (int) CentCommTemperature.Custom;
        };
        ParallaxSelector.OnItemSelected += args => ParallaxSelector.SelectId(args.Id);
        WeatherSelector.OnItemSelected += args => WeatherSelector.SelectId(args.Id);
        CelsiusInput.IsValid = value => float.IsFinite(value) &&
            value >= CentCommTransferSettings.MinCelsius && value <= CentCommTransferSettings.MaxCelsius;
        TransferButton.OnPressed += _ =>
        {
            if (ParallaxSelector.SelectedMetadata is not string parallax)
                return;
            TransferButton.Disabled = true;
            OnTransfer?.Invoke(new CentCommTransferRequest(parallax,
                (CentCommTemperature) TemperatureSelector.SelectedId, CelsiusInput.Value,
                WeatherSelector.SelectedMetadata as string));
        };
    }

    public void SetState(CentCommTransferState state)
    {
        if (!_parallaxes.SequenceEqual(state.Parallaxes))
        {
            var selected = ParallaxSelector.ItemCount > 0 ? ParallaxSelector.SelectedMetadata as string : "Default";
            _parallaxes = state.Parallaxes;
            Populate(ParallaxSelector, _parallaxes, selected);
        }

        if (!_weather.SequenceEqual(state.Weather) || WeatherSelector.ItemCount == 0)
        {
            var selected = WeatherSelector.ItemCount > 0 ? WeatherSelector.SelectedMetadata as string : null;
            _weather = state.Weather;
            Populate(WeatherSelector, _weather, selected, weather: true);
        }

        StatusLabel.SetMessage(state.Status);
        TransferButton.Disabled = !state.CanStart || ParallaxSelector.ItemCount == 0;
    }

    private static void Populate(OptionButton selector, string[] options, string? selected, bool weather = false)
    {
        selector.Clear();
        var loc = IoCManager.Resolve<ILocalizationManager>();
        if (weather)
            selector.AddItem(Loc.GetString("centcomm-transfer-weather-none"));
        foreach (var option in options)
        {
            var index = selector.ItemCount;
            var label = weather && loc.TryGetString($"centcomm-transfer-weather-{option}", out var localized)
                ? localized : option;
            selector.AddItem(label);
            selector.SetItemMetadata(index, option);
            if (option == selected)
                selector.Select(index);
        }
    }
}
