// Мёртвый Космос, Союз-1, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-soyuz/master/LICENSES/LICENSE.TXT

using Content.Shared.DeadSpace._Soyuz.Telecommunications;
using Content.Shared.Radio;
using System.Linq;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.DeadSpace._Soyuz.Telecommunications;

[GenerateTypedNameReferences]
public sealed partial class TelecommunicationBlacklistConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<NetEntity>? OnTargetSelected;
    public event Action<NetEntity, List<ProtoId<RadioChannelPrototype>>>? OnApply;
    public event Action? OnRefresh;

    private readonly Dictionary<ProtoId<RadioChannelPrototype>, CheckBox> _channelCheckboxes = new();
    private NetEntity? _selectedMind;

    public TelecommunicationBlacklistConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
        ApplyButton.OnPressed += _ => ApplyDraft();
    }

    public void UpdateState(TelecommunicationBlacklistConsoleState state)
    {
        LockedPanel.Visible = state.Locked;
        MainPanel.Visible = !state.Locked;

        if (state.Locked)
        {
            _selectedMind = null;
            ChannelList.RemoveAllChildren();
            _channelCheckboxes.Clear();
            return;
        }

        PopulateRoster(state.Roster, state.SelectedMind);
        PopulateDetails(state);
    }

    private void PopulateRoster(
        IReadOnlyList<TelecommunicationBlacklistRosterEntry> roster,
        NetEntity? selectedMind)
    {
        RosterList.RemoveAllChildren();
        RosterEmptyLabel.Visible = roster.Count == 0;

        foreach (var entry in roster)
        {
            var target = entry.Mind;
            var button = new Button
            {
                Text = $"{entry.Name}\n{entry.JobTitle}",
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = selectedMind == target,
                Margin = new Thickness(0, 0, 0, 4),
            };

            button.OnPressed += _ => SelectTarget(target);
            RosterList.AddChild(button);
        }
    }

    private void PopulateDetails(TelecommunicationBlacklistConsoleState state)
    {
        _selectedMind = state.SelectedMind;
        var selected = state.SelectedMind is { } selectedMind
            ? state.Roster.FirstOrDefault(entry => entry.Mind == selectedMind)
            : null;

        var hasSelection = selected != null;
        NoSelectionPanel.Visible = !hasSelection;
        DetailsPanel.Visible = hasSelection;
        ApplyButton.Disabled = !hasSelection;

        ChannelList.RemoveAllChildren();
        _channelCheckboxes.Clear();

        if (selected == null)
            return;

        TargetNameLabel.Text = Loc.GetString(
            "telecommunication-blacklist-console-target-name",
            ("name", selected.Name));
        TargetJobLabel.Text = Loc.GetString(
            "telecommunication-blacklist-console-target-job",
            ("job", selected.JobTitle));

        var localizedChannels = new List<(ProtoId<RadioChannelPrototype> Id, string Name)>();
        foreach (var channelId in state.Channels)
        {
            if (_prototype.TryIndex(channelId, out RadioChannelPrototype? channel))
                localizedChannels.Add((channelId, channel.LocalizedName));
        }

        foreach (var (channelId, channelName) in localizedChannels.OrderBy(channel => channel.Name))
        {
            var checkBox = new CheckBox
            {
                Text = channelName,
                Pressed = state.BlockedChannels.Contains(channelId),
                HorizontalExpand = true,
                Margin = new Thickness(0, 0, 0, 3),
            };

            _channelCheckboxes[channelId] = checkBox;
            ChannelList.AddChild(checkBox);
        }
    }

    private void SelectTarget(NetEntity target)
    {
        // Invalidate the current local draft immediately. The server response will populate a fresh one.
        _selectedMind = null;
        DetailsPanel.Visible = false;
        NoSelectionPanel.Visible = true;
        ApplyButton.Disabled = true;
        ChannelList.RemoveAllChildren();
        _channelCheckboxes.Clear();

        OnTargetSelected?.Invoke(target);
    }

    private void ApplyDraft()
    {
        if (_selectedMind is not { } target)
            return;

        var blockedChannels = _channelCheckboxes
            .Where(entry => entry.Value.Pressed)
            .Select(entry => entry.Key)
            .ToList();

        OnApply?.Invoke(target, blockedChannels);
    }
}
