using Content.Client.Administration.Managers;
using Content.Shared.Administration;
using Content.Shared.DeadSpace.Administration.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Tabs
{
    [GenerateTypedNameReferences]
    public sealed partial class RoundTab : Control
    {
        [Dependency] private readonly IClientConsoleHost _console = default!;
        [Dependency] private readonly IClientAdminManager _admin = default!;

        public RoundTab()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            StartRound.OnPressed += _ => _console.ExecuteCommand("startround");
            EndRound.OnPressed += _ => _console.ExecuteCommand("endround");
            RestartRound.OnPressed += _ => _console.ExecuteCommand("restartround");
            RestartRoundNow.OnPressed += _ => _console.ExecuteCommand("restartroundnow");
            CentCommTransferButton.OnPressed += _ =>
            {
                if (_admin.HasFlag(AdminFlags.Fun))
                    _console.ExecuteCommand("centcomm_transfer");
            };
            _admin.AdminStatusUpdated += RefreshTransferButton;
            RefreshTransferButton();
        }

        private void RefreshTransferButton()
        {
            CentCommTransferButton.Visible = _admin.HasFlag(AdminFlags.Fun);
            CentCommTransferButton.Disabled = !_admin.HasFlag(AdminFlags.Fun);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _admin.AdminStatusUpdated -= RefreshTransferButton;
            base.Dispose(disposing);
        }

        // DS14-start
        public void UpdateAutoMapVoteState(AutoMapVoteAdminState? state)
        {
            AutoMapVoteControl.UpdateState(state);
        }
        // DS14-end
    }
}
