using System.Linq;
using System.Numerics;
using Content.Client.DeadSpace.Access;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using static Content.Shared.Access.Components.IdCardConsoleComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class IdCardConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly ILogManager _logManager = default!;
        private readonly ISawmill _logMill = default!;

        private readonly IdCardConsoleBoundUserInterface _owner;

        // CCVar.
        private int _maxNameLength;
        private int _maxIdJobLength;

        // DS14-start
        // private AccessLevelControl _accessButtons = new();
        private readonly IdCardAccessEditor _accessButtons = new();
        private readonly List<string> _jobPrototypeIds = new() { string.Empty };
        private HashSet<ProtoId<AccessLevelPrototype>> _currentAccess = new();
        private readonly List<ProtoId<AccessLevelPrototype>> _basicAccessLevels;
        private readonly List<ProtoId<AccessLevelPrototype>> _extendedAccessLevels;
        // DS14-end

        private string? _lastFullName;
        private string? _lastJobTitle;
        // private string? _lastJobProto; // DS14: job assignments are submitted only on explicit selection.

        // private static ProtoId<JobPrototype> _defaultJob = "Passenger"; // DS14: preserve hidden/current professions.

        public IdCardConsoleWindow(IdCardConsoleBoundUserInterface owner, IPrototypeManager prototypeManager,
            List<ProtoId<AccessLevelPrototype>> accessLevels,
            List<ProtoId<AccessLevelPrototype>> basicAccessLevels,
            List<ProtoId<AccessLevelPrototype>> extendedAccessLevels,
            bool isTaipan, // DS14
            bool hasDismissal) // DS14
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            // DS14-start
            var root = UserInterfaceManager.RootControl;
            var viewport = (Vector2) root.Window.RenderTarget.Size / root.UIScale;
            SetSize = Vector2.Min(new Vector2(880, 640), Vector2.Max(viewport - new Vector2(32), new Vector2(640, 400)));
            MinSize = Vector2.Min(new Vector2(700, 460), SetSize);
            // DS14-end
            _logMill = _logManager.GetSawmill(SharedIdCardConsoleSystem.Sawmill);

            _owner = owner;
            // DS14-start
            _basicAccessLevels = basicAccessLevels;
            _extendedAccessLevels = extendedAccessLevels;
            // DS14-end

            _maxNameLength = _cfgManager.GetCVar(CCVars.MaxNameLength);
            _maxIdJobLength = _cfgManager.GetCVar(CCVars.MaxIdJobLength);

            FullNameLineEdit.OnTextEntered += _ => SubmitData();
            FullNameLineEdit.IsValid = s => s.Length <= _maxNameLength;
            FullNameLineEdit.OnTextChanged += _ =>
            {
                FullNameSaveButton.Disabled = FullNameLineEdit.Text == _lastFullName; // DS14
            };
            FullNameSaveButton.OnPressed += _ => SubmitData();

            JobTitleLineEdit.OnTextEntered += _ => SubmitData();
            JobTitleLineEdit.IsValid = s => s.Length <= _maxIdJobLength;
            JobTitleLineEdit.OnTextChanged += _ =>
            {
                JobTitleSaveButton.Disabled = JobTitleLineEdit.Text == _lastJobTitle;
            };
            JobTitleSaveButton.OnPressed += _ => SubmitData();

            // DS14-start
            var jobs = _prototypeManager.EnumeratePrototypes<JobPrototype>()
                .Where(job => job.OverrideConsoleVisibility.GetValueOrDefault(job.SetPreference))
                .Where(job => isTaipan ? job.IsTaipan : !job.IsTaipan)
                .ToList();
            // DS14-end

            jobs.Sort((x, y) => string.Compare(x.LocalizedName, y.LocalizedName, StringComparison.CurrentCulture));

            JobPresetOptionButton.AddItem(Loc.GetString("id-card-console-window-no-job-preset"), 0); // DS14
            foreach (var job in jobs)
            {
                _jobPrototypeIds.Add(job.ID);
                JobPresetOptionButton.AddItem(Loc.GetString(job.Name), _jobPrototypeIds.Count - 1);
            }

            SelectAllButton.OnPressed += _ =>
            {
                SetAllAccess(true, currentCategoryOnly: true); // DS14
                SubmitData();
            };

            DeselectAllButton.OnPressed += _ =>
            {
                SetAllAccess(false, currentCategoryOnly: true); // DS14
                SubmitData();
            };

            JobPresetOptionButton.OnItemSelected += SelectJobPreset;
            _accessButtons.Populate(accessLevels, prototypeManager);
            AccessLevelControlContainer.AddChild(_accessButtons);

            _accessButtons.AccessChanged += () => SubmitData(); // DS14: also covers controls rebuilt after changing station.

            // DS14-Start
            BasicAccessButton.Visible = _basicAccessLevels.Count > 0;
            ExtendedAccessButton.Visible = _extendedAccessLevels.Count > 0;
            BasicAccessButton.OnPressed += _ => SetAccessPreset(_basicAccessLevels);
            ExtendedAccessButton.OnPressed += _ => SetAccessPreset(_extendedAccessLevels);
            DismissButton.Visible = hasDismissal;
            // DS14-End
        }

        /// <param name="enabled">If true, every individual access button will be pressed. If false, each will be depressed.</param>
        private void SetAllAccess(bool enabled, bool currentCategoryOnly = false) // DS14
        {
            // DS14-start
            var buttons = currentCategoryOnly
                ? _accessButtons.CurrentAccessLevels.Select(id => _accessButtons.ButtonsList[id])
                : _accessButtons.ButtonsList.Values;
            // DS14-end
            foreach (var button in buttons) // DS14
            {
                if (!button.Disabled && button.Pressed != enabled)
                    button.Pressed = enabled;
            }
        }

        private void SelectJobPreset(OptionButton.ItemSelectedEventArgs args)
        {
            // DS14-start
            if (args.Id <= 0 || args.Id >= _jobPrototypeIds.Count)
                return;
            // DS14-end
            if (!_prototypeManager.TryIndex(_jobPrototypeIds[args.Id], out JobPrototype? job))
            {
                return;
            }

            JobTitleLineEdit.Text = Loc.GetString(job.Name);
            args.Button.SelectId(args.Id);

            SetAllAccess(false);

            // this is a sussy way to do this
            foreach (var access in job.Access)
            {
                if (_accessButtons.ButtonsList.TryGetValue(access, out var button) && !button.Disabled)
                {
                    button.Pressed = true;
                }
            }

            foreach (var group in job.AccessGroups)
            {
                if (!_prototypeManager.Resolve(group, out AccessGroupPrototype? groupPrototype))
                {
                    continue;
                }

                foreach (var access in groupPrototype.Tags)
                {
                    if (_accessButtons.ButtonsList.TryGetValue(access, out var button) && !button.Disabled)
                    {
                        button.Pressed = true;
                    }
                }
            }

            SubmitData(job.ID); // DS14: only this action assigns a different profession.
        }

        public void UpdateState(IdCardConsoleBoundUserInterfaceState state)
        {
            PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            // DS14-start
            UpdateCardPresentation(PrivilegedIdLabel, PrivilegedIdJobLabel, state.IsPrivilegedIdPresent,
                state.PrivilegedIdFullName, state.PrivilegedIdJobTitle, state.PrivilegedIdName);
            // DS14-end

            TargetIdButton.Text = state.IsTargetIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            // DS14-start
            UpdateCardPresentation(TargetIdLabel, TargetIdJobLabel, state.IsTargetIdPresent,
                state.TargetIdFullName, state.TargetIdJobTitle, state.TargetIdName);
            // DS14-end

            var interfaceEnabled =
                state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && state.IsTargetIdPresent;

            // DS14-start
            var fullNameDirty = _lastFullName != null && FullNameLineEdit.Text != _lastFullName;
            var jobTitleDirty = _lastJobTitle != null && JobTitleLineEdit.Text != _lastJobTitle;
            // DS14-end

            FullNameLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            FullNameLineEdit.Editable = interfaceEnabled;
            if (!fullNameDirty)
            {
                FullNameLineEdit.Text = state.TargetIdFullName ?? string.Empty;
            }

            FullNameSaveButton.Disabled = !interfaceEnabled || !fullNameDirty;

            JobTitleLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            JobTitleLineEdit.Editable = interfaceEnabled;
            if (!jobTitleDirty)
            {
                JobTitleLineEdit.Text = state.TargetIdJobTitle ?? string.Empty;
            }

            JobTitleSaveButton.Disabled = !interfaceEnabled || !jobTitleDirty;

            JobPresetOptionButton.Disabled = !interfaceEnabled;
            // DS14-start
            BasicAccessButton.Disabled = !interfaceEnabled;
            ExtendedAccessButton.Disabled = !interfaceEnabled;
            // Don't clobber ConfirmButton's own transient disabled state while it's mid-"are you
            // sure" cooldown - only force it here outside of that window.
            if (!DismissButton.IsConfirming)
                DismissButton.Disabled = !interfaceEnabled;
            // DS14-end

            // DS14-start
            SelectAllButton.Disabled = !interfaceEnabled;
            DeselectAllButton.Disabled = !interfaceEnabled;
            _currentAccess = state.TargetIdAccessList?.ToHashSet() ?? new();
            _accessButtons.Populate(state.AvailableAccessList, _prototypeManager);
            _accessButtons.UpdateState(_currentAccess.ToList(), interfaceEnabled
                ? state.AllowedModifyAccessList?.ToList() ?? new()
                : new());
            // DS14-end

            var jobIndex = _jobPrototypeIds.IndexOf(state.TargetIdJobPrototype);
            // If the job index is < 0 that means they don't have a job registered in the station records
            // or the IdCardComponent's JobPrototype field.
            // For example, a new ID from a box would have no job index.
            if (jobIndex < 0)
            {
                jobIndex = 0; // DS14: display a placeholder instead of silently assigning Passenger.
            }

            // DS14-start
            if (jobIndex >= 0 && jobIndex < JobPresetOptionButton.ItemCount)
            {
                JobPresetOptionButton.SelectId(jobIndex);
            }
            else if (JobPresetOptionButton.ItemCount > 0)
            {
                JobPresetOptionButton.SelectId(0);
            }
            // DS14-end

            _lastFullName = state.TargetIdFullName;
            _lastJobTitle = state.TargetIdJobTitle;
            // _lastJobProto = state.TargetIdJobPrototype; // DS14
        }

        // DS14-start
        private static void UpdateCardPresentation(RichTextLabel ownerLabel, Label jobLabel, bool present,
            string? owner, string? job, string entityName)
        {
            ownerLabel.SetMessage(!present ? Loc.GetString("id-card-console-window-empty-slot")
                : string.IsNullOrWhiteSpace(owner) ? Loc.GetString("id-card-console-window-no-owner") : owner);
            ownerLabel.ToolTip = present ? entityName : null;
            jobLabel.Text = !present ? Loc.GetString("id-card-console-window-insert-hint")
                : string.IsNullOrWhiteSpace(job) ? Loc.GetString("id-card-console-window-no-job") : job;
            jobLabel.ToolTip = jobLabel.Text;
        }
        // DS14-end

        // DS14-Start
        private void SetAccessPreset(List<ProtoId<AccessLevelPrototype>> targetList)
        {
            if (targetList.Count == 0)
                return;

            SetAllAccess(false);

            foreach (var access in targetList)
            {
                if (_accessButtons.ButtonsList.TryGetValue(access, out var button) && !button.Disabled)
                    button.Pressed = true;
            }

            SubmitData();
        }
        // DS14-End

        private void SubmitData(ProtoId<JobPrototype>? selectedJob = null) // DS14
        {
            // DS14-start
            // Keep access that is hidden or not editable by the inserted authorization card.
            var access = _currentAccess.ToHashSet();
            foreach (var (id, button) in _accessButtons.ButtonsList)
            {
                if (button.Disabled)
                    continue;

                if (button.Pressed)
                    access.Add(id);
                else
                    access.Remove(id);
            }
            // DS14-end

            _owner.SubmitData(
                FullNameLineEdit.Text,
                JobTitleLineEdit.Text,
                access.ToList(), // DS14
                selectedJob ?? new ProtoId<JobPrototype>(string.Empty)); // DS14
        }
    }
}
