// Мёртвый Космос, Licensed under custom terms with restrictions on public hosting and commercial use, full text: https://raw.githubusercontent.com/dead-space-server/space-station-14-soyuz/master/LICENSE.TXT

using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared.DeadSpace._Soyuz.MeteorDefense;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.DeadSpace._Soyuz.MeteorDefense;

[GenerateTypedNameReferences]
public sealed partial class MeteorDefenseWindow : FancyWindow
{
    public event Action<bool>? SetEnabled;
    public event Action<float>? SetMaxCharge;
    private bool _enabled;
    private float _maxAllowed;

    public MeteorDefenseWindow()
    {
        RobustXamlLoader.Load(this);
        ApplyButton.OnPressed += _ => ApplyCapacity();
        CapacityInput.OnTextEntered += _ => ApplyCapacity();
        ToggleButton.OnPressed += _ => SetEnabled?.Invoke(!_enabled);
    }

    private void ApplyCapacity()
    {
        if (!float.TryParse(CapacityInput.Text, NumberStyles.Float, CultureInfo.CurrentCulture, out var value)
            || !float.IsFinite(value) || value < 0 || value > _maxAllowed)
        {
            ErrorLabel.Text = Loc.GetString("meteor-defense-invalid-capacity");
            return;
        }

        ErrorLabel.Text = "";
        SetMaxCharge?.Invoke(value);
    }

    public void UpdateState(MeteorDefenseBoundUserInterfaceState state)
    {
        _enabled = state.Enabled;
        _maxAllowed = state.MaxAllowedCharge;
        StatusLabel.Text = Loc.GetString(state.Enabled ? "meteor-defense-status-on" : "meteor-defense-status-off");
        ChargeLabel.Text = Loc.GetString("meteor-defense-charge", ("current", state.CurrentCharge), ("max", state.MaxCharge));
        ReadyLabel.Text = Loc.GetString("meteor-defense-ready", ("count", state.ReadyIntercepts));
        CostLabel.Text = Loc.GetString("meteor-defense-cost", ("value", state.EnergyPerIntercept));
        RateLabel.Text = Loc.GetString("meteor-defense-rate", ("value", state.MaxChargeRate));
        LimitLabel.Text = Loc.GetString("meteor-defense-limit", ("value", state.MaxAllowedCharge));
        CapacityInput.PlaceHolder = state.MaxCharge.ToString(CultureInfo.CurrentCulture);
        ToggleButton.Text = Loc.GetString(state.Enabled ? "meteor-defense-disable" : "meteor-defense-enable");
    }
}
