- type: playTimeTracker
  id: JobPolitruk

- type: playTimeTracker
  id: JobPolitkom

- type: playTimeTracker
  id: JobNavyCaptain

- type: playTimeTracker
  id: JobNavyOfficer

- type: playTimeTracker
  id: JobNavyEngineer

- type: playTimeTracker
  id: JobNavyMedical

- type: playTimeTracker
  id: JobOperatorGS

- type: playTimeTracker
  id: JobOfficerGS

- type: playTimeTracker
  id: JobGeneralStaffKGB

- type: playTimeTracker
  id: JobOKGB
